---
title: "SOC 301-01: Social Statistics"
author: "Chester Ismay"
output:
  ioslides_presentation:
    incremental: no
    logo: ../figs/boxer.jpg
    fig.align: center
    widescreen: true
subtitle: Working on the RStudio Server
---


## Learning Quote of the Day {.flexbox .vcenter}

> "You don't learn to walk by following rules. 

> You learn by doing, and by falling over." 

- Richard Branson

## Sharing RStudio Project

DEMO

## Install packages

- Remember that you need to select R 3.2 in the top right corner of RStudio Server

```{r eval=FALSE}
needed_pkgs <- c("nycflights13", "dplyr", "ggplot2", "knitr", 
  "ggplot2movies", "dygraphs", "rmarkdown", "mosaic", "tibble")

new.pkgs <- needed_pkgs[!(needed_pkgs %in% installed.packages())]

if(length(new.pkgs)) {
  install.packages(new.pkgs, repos = "http://cran.rstudio.com")
}
```

# Plicker time!

## Course Textbook

<http://ismayc.github.io/moderndiver-book>

PDF version also available: <https://ismayc.github.io/moderndiver-book/ismay.pdf>

## Working in RStudio with R Markdown

DEMO

## Next class (Monday) plans

- Answer questions for first 10-15 minutes to help prepare you for the quiz
- You'll have the chance to talk about anything you are struggling with in groups as well for a few minutes
- Quiz #1 testing your knowledge of using R, RStudio, and R Markdown based on the
[Getting Used to R, RStudio, and R Markdown](http://ismayc.github.io/rbasics-book) book
    - First you'll take the quiz individually
    - Then we will take a break in class and you'll take the quiz again in groups
    - Then we'll go over it in class
- Lastly, I'll show you how to do a few more things in R and we'll begin Tidy data in MODERN DIVE.

## Assignment for Monday

- Read Chapter 3 of MODERN DIVE textbook
- Complete LC3.1 - LC3.8 and other questions in PS2 by 10 AM on Monday
- Start on Lab 1
    - Lab 1 draft (must attempt all exercises for credit) due on Tuesday at 3 PM
    - Great way to study for the quiz

## Minute Papers

- Now that you've worked with R some, how do you plan to practice working with it more to begin studying for the quiz?

- Remember that you'll need to quiz yourself frequently if you want to learn the material.  I'll be able to pretty easily identify students that are studying on their own and those that are not quizzing themselves frequently.  

- Keep on studying as often as you can and checking yourself for understanding!


