# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chester Ismay
email: chester.ismay@flatironschool.com
position: Director of Data Science Education
institution1: Flatiron School
inst_link1: https://flatironschool.com/
#description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chester.rbind.io" # the base hostname & protocol for your site
twitter_username: old_man_chester
github_username:  ismayc

# Build settings
markdown: kramdown