---
title: "Roadless USA"
output:
  ioslides_presentation:
    incremental: true
---

```{r setup, include=FALSE}
library(knitr)
options(digits=3)
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(dplyr)
library(ggplot2)
library(ggmap)
```

## 

```{r echo = FALSE, cache=TRUE}
d <- read.csv("roadless-data.csv", header = TRUE)
m <- get_map(location = c(-125, 25, -65, 50), source="stamen", maptype = "terrain-background")

# sample locations
ggmap(m) + 
  geom_point(data = d, aes(x = longitude, y = latitude), alpha = .6)
```

##

```{r echo = FALSE}
# within continental US
ggmap(m) + 
  geom_point(data = d, aes(x = longitude, y = latitude, color = factor(withinContinent)), alpha = .6) +
  scale_colour_manual(values=c("red", "blue"), guide = FALSE)
```


##

```{r echo = FALSE}
# within continental US
d2 <- filter(d, withinContinent == 1)
ggmap(m) + 
  geom_point(data = d2, aes(x = longitude, y = latitude, color = factor(withinContinent)), alpha = .6) +
  scale_colour_manual(values=c("blue"), guide = FALSE)
```

##

```{r echo = FALSE}
ggmap(m) + 
  geom_point(data = d2, aes(x = longitude, y = latitude, color = factor(within1mile)), alpha = .8) +
  scale_colour_manual(values=c("green", "blue"), guide = FALSE)
```

