---
title: "Week Three, Day 1"
author: "Chester Ismay"
date: "February 7, 2016"
output: html_document
---

***

```{r setup, include=FALSE}
# List of useful packages
pkg <- c("dplyr", "ggplot2", "knitr")

# Check if packages are not installed and assign the
# names of the uninstalled packages to the variable new.pkg
new.pkg <- pkg[!(pkg %in% installed.packages())]

# If there are any packages in the list that aren't installed,
# install them
if (length(new.pkg)) {
  install.packages(new.pkg, repos = "http://cran.rstudio.com")
}

# Load the packages into the current environment
library(knitr)
library(dplyr)
library(ggplot2)

# Set number of digits to display
options(digits = 3)
```

1. Remind them I will be gone next Monday and Wednesday
  - Class may meet in Physics 123 (Current classroom)

2. Review quiz

3. Recap of Chapter 1
  - Ask them for main ideas
  - Differences between descriptive/inferential statistics
  - Describing data using graphics & summary measures

4. Begin with Plicker question 1
  - Come back to correct answer in a bit

5. Switch to slides

6. Inflatable globe

  - Put Table on chalkboard
  
  Event | Count | Probability
  ------|-------|------------
  water |       |             
  land  |       |             

  - We explain that the globe will be tossed around the class, and we instruct students to hit the globe with the tip of their index finger when it comes to them. When they do, they are to shout “water!” if their finger touches water, or “land!” if their finger touches land. (Bag of tricks)
  
7. Back to slides

8. General Addition Rule
  - Let $S8$ = the event that the sum is 8 when tossing two fair dice
  - Let $O6$ = the event that one of the dice is a 6
  - $\mathbb{P}(S8) = 5/36$, $\mathbb{P}(O6) = 11/36$ so
  $\mathbb{P}(S8 \text{ or } O6) = 16/36$?
  - $S8 \text{ and } O6$ - the overlap of the two events, sum is 8 AND at least one is 6
  - $\mathbb{P}(S8 \text{ and } O6) = 2/36$
  - Trying to find $\mathbb{P}(S8 \text{ or } O6) = 5/36 + 11/36 - 2/36 = 14/36$

9. Addition Rule for Disjoint Outcomes

10. Go to Plicker Q 2

11. Back to slides - Go over Plicker 2 answer (D)

11. Continue on slides - Probability Distribution
