---
title: "Week Four, Day 3"
author: "Chester Ismay"
date: "February 19, 2016"
output: html_document
---

***

```{r setup, include=FALSE}
# List of useful packages
pkg <- c("dplyr", "ggplot2", "knitr")

# Check if packages are not installed and assign the
# names of the uninstalled packages to the variable new.pkg
new.pkg <- pkg[!(pkg %in% installed.packages())]

# If there are any packages in the list that aren't installed,
# install them
if (length(new.pkg)) {
  install.packages(new.pkg, repos = "http://cran.rstudio.com")
}

# Load the packages into the current environment
library(knitr)
library(dplyr)
library(ggplot2)

# Set number of digits to display
# options(digits = 3)
```

0. Update on PS4

1. Hand back PS3

2. Recap
  - Put Binomial probability mass function on the board
  - $Y \sim Bin(n, p)$
  - $\mathbb{P} (Y = y) = \binom{n}{y} p^y (1-p)^{n-y}$
  - $\mathbb{E}(Y) = np$, $\mathbb{V}(Y) = np(1-p)$, $\mathbb{S}(Y) = \sqrt{np(1-p)}$
  - Independent trials Model
      - __B__ inary outcomes: There are two possible outcomes for each trial (success or failure).
      - __I__ ndependent trials: The outcomes of the trials are independent of each other.
      - __*n*__ is fixed: The number of trials, _n_, is fixed in advance.
      - __S__ ame value of _p_: The probability of a success on a single trial is the same for all trials.
  
3. Go over slides for Binomial - How many quizzes to print for both sections of MATH 141 for today?
  - Load up applet and change parameters to $n = 38$, $p = 0.93$
  - Ask what happens to the distribution as I change $p$
  - Show that formulas are also given as well as mean and variance calculations
  - Watch how the distribution changes as $p$ changes
  - What about $n$ changing?
  
4. Introduce Poisson with Justices example

5. Provide background on Poisson

6. Go over Poisson formulas (from applet) and assumptions

7. Hand out quiz

8. Go over quiz solutions