---
title: "Week One Lab"
author: "Chester Ismay"
date: "January 26, 2016"
output: html_document
---

***

0. Load up the Labs page.  Get everyone to go there first.
1. Greeting and welcome to lab.  My name is Chester Ismay and Andrew Bray are teaching parallel sessions of the course so in these labs you'll see folks from my section and also from Andrew's session.
2. These labs will be done using R and the RStudio Server which are based on open-source free technologies.  If you'd like to get RStudio installed on your machine, go to this link for instructions I put together.  We will be using the RStudio Server for all labs this semester.  If you have an internet connection, you will be analyzing data in something that looks exactly like if you were running RStudio on your own machine.
3. My goal is for everyone is 
  - to have successfully signed into the RStudio Server
  - to created a Shared Project with us and the lab TA Dean
  - start looking at the data for this lab
4.  Likely there will be some portions of labs that you'll need to do on your own
  - Try to get as much done as possible during the lab while we are here to help you
5. Click on RStudio-dev link.
  - Sign in using your usual email credentials w/o @reed.edu
  - Your page should look something like this
6. Click to quit the current R session
    - This will show you a list of projects
    - Open New Session.  It will take a bit to load.
    - We are now going to create a new Project
      - File -> New Project -> New Directory -> Empty Project
      - Enter your username-labs.  The project by default will go into your
      home directory on the server denoted by the ~.
      - Click Create Project
7. We are now going to share that project with Andrew, Dean, and myself
    - Enter `abray`, then click Add
    - Enter `cismay`, Add
    - Enter `youngde`, Add
    - Click OK
8.  What that does is gives the three of us access to your files at any time
  - This will be really helpful if you are having issues and would like help.  We don't (AND WON'T) be emailing files back and forth.  We can go see why you might be having an error.
  - You will not be submitting anything to Moodle.
  - This is how you will be receiving feedback from us on the labs.
  - The labs will be due each week at 11:59 PM.  After that time, we will be reviewing them so just save all your work and then we will go in to the Shared Project.
9. From my end, I'll give you a feel for how this looks.  I'm going to go enter someone's Shared Project.
  - Now I can create a new file and save it.
  - If USER opens up the file we can be editing it at the same time.  This works much like Google Docs.

#### R Markdown  
  
10. R Markdown was detailed in the videos you watched for today.
11. Create a folder called lab1 (NO SPACES)
12. Now go get template for today's lab from the Labs page
12. Click on Intro to R and RStudio
  - This is instructions for the lab
13. Ctrl-Click on template and save to Desktop
  - This will be the template RMarkdown file you can use as a basis for your lab
14. Break for how files are saved
15. Upload to server
16. Open the lab template.
  - Delete the space at the top of the document
17. Knit to HTML
17. Change to View Pane
18. Zoom in to `arbuthnot` data
  - Christening data from churches in London with names of children christened
19.  The labs have lots of exposition to walk through how to get things set up
20. Exercises are what we want you to do.  Fill in the needed spots in your template.

# WHITE SPACE IS IMPORTANT

21. Don't just blindly copy and paste code
  - Think carefully about what is going on and be sure to read what we have written in text above the code chunks
    
    