on:
  schedule:
#    - cron: "*/10 * * * *"
    - cron: "0 8,13 * * *"
  push:
    branches: [main, master]
  workflow_dispatch:

name: build-nba-webpage

jobs:
  build-nba-webpage:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.TOKEN }}
#      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck remotes reticulate

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: setup r-reticulate venv
        shell: Rscript {0}
        run: |
          python_packages <- c("pandas", "nba_api")

          library(reticulate)
          virtualenv_create("r-reticulate", Sys.which("python"))
          virtualenv_install("r-reticulate", python_packages)

          path_to_python <- virtualenv_python("r-reticulate")
          writeLines(sprintf("RETICULATE_PYTHON=%s", path_to_python),
                     Sys.getenv("GITHUB_ENV"))

# renv code start (doesn't work)
      # - uses: actions/checkout@v3
      # - uses: r-lib/actions/setup-r@v2
      # - uses: r-lib/actions/setup-renv@v2      
      # - name: Set RENV_PATHS_ROOT
      #   shell: bash
      #   run: |
      #     echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV
      # - name: Install and activate renv
      #   run: |
      #     install.packages("renv")
      #     install.packages("yaml")
      #     renv::upgrade()
      #     renv::activate()
      #   shell: Rscript {0}
      # - name: Cache packages
      #   uses: actions/cache@v1
      #   with:
      #     path: ${{ env.RENV_PATHS_ROOT }}
      #     key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-renv-
      # 
      # - name: Restore packages
      #   shell: Rscript {0}
      #   run: |
      #     renv::restore()
# renv code end

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ismayc/ismayc.github.io
          token: ${{ secrets.TOKEN }}

      - name: Pull changes
        run: git pull origin master

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git remote set-url origin https://github.com/ismayc/ismayc.github.io.git
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
 
      - name: Build webpage
        run: |
          source("nba-over-under-2024-2025/make_plot_html.R")
        shell: Rscript {0} 

      - uses: r-lib/actions/setup-renv@v2            

      - name: Push changes
        run: |
          git commit -am "GitHub Actions NBA page build"
          git push origin master        
          
      - name: Session info
        run: |
          options(width = 100)
          install.packages("sessioninfo")
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
