name: build-nba-webpage
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  check-date:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.date_check.outputs.should_run }}
    steps:
      - id: date_check
        run: |
          CURRENT_DATE=$(date -u +%Y-%m-%d)
          CUTOFF_DATE="2025-04-15"
          if [[ "$CURRENT_DATE" < "$CUTOFF_DATE" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
          
  build-nba-webpage:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    needs: check-date
    if: ${{ needs.check-date.outputs.should_run == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      WORKON_HOME: ./.virtualenvs
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Fix macOS dependencies
        run: |
          brew install pkg-config
          brew install icu4c
          brew link --force icu4c
          
          echo "PKG_CONFIG_PATH=$(brew --prefix icu4c)/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$(brew --prefix icu4c)/include" >> $GITHUB_ENV
          echo "LDFLAGS=-L$(brew --prefix icu4c)/lib" >> $GITHUB_ENV
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
      
      - name: Install stringi manually with binary
        run: |
          # Try to install stringi as a binary package first
          Rscript -e "install.packages('stringi', type = 'binary', repos = 'https://cloud.r-project.org/')"
          
          # Check if successful, if not, create specific compiler flags for stringi
          Rscript -e "if(!requireNamespace('stringi', quietly = TRUE)) {
            # Create special Makevars for stringi build
            dir.create('~/.R', showWarnings = FALSE)
            cat('CPPFLAGS=-I$(brew --prefix icu4c)/include -DU_SHOW_CPLUSPLUS_API=0\\n', file='~/.R/Makevars')
            cat('LDFLAGS=-L$(brew --prefix icu4c)/lib\\n', append=TRUE, file='~/.R/Makevars')
            install.packages('stringi', type='source', repos='https://cloud.r-project.org/')
          }"
      
      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck remotes reticulate
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Setup Python virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pandas nba_api
          echo "RETICULATE_PYTHON=$(pwd)/venv/bin/python" >> $GITHUB_ENV
        shell: bash
      
      - name: Build webpage
        run: |
          Rscript nba-over-under-2024-2025/make_plot_html.R
        shell: bash
      
      - name: Push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "GitHub Actions NBA page build" || echo "No changes to commit"
          git push origin master
      
      - name: Session info
        run: |
          Rscript -e "install.packages('sessioninfo')"
          Rscript -e "sessioninfo::session_info()"
        shell: bash
